[package]
name = "hexcat"
version = "1.0.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "MIT/Apache-2.0"
description = "Utility to output a file's contents in Rust's hexidecimal notation."

[[bin]]
name = "hexcat"
path = "main.rs"
